## 1.Loading lib numpy

In [1]:
import numpy as np

### creating numpy array


In [7]:
a = [2, 4, 6, 8, 10]
b = np.array(list1)

In [8]:
b

array([ 2,  4,  6,  8, 10])

In [9]:
a

[2, 4, 6, 8, 10]

### checking type of function 

In [10]:
type(a)

list

In [11]:
type(b)

numpy.ndarray

#### numpy allows for vectorized operations

In [12]:
list1 = a
arr1 = b

In [13]:
list1 + 1

TypeError: can only concatenate list (not "int") to list

In [14]:
arr1 + 1

array([ 3,  5,  7,  9, 11])

In [15]:
list2 = [[9, 0, 4, 6], [4, 6, 2, 1]]
arr2 = np.array(list2)

In [16]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

#### float array (changing datatype froma list)

In [17]:
arr2 = np.array(list2, dtype = 'float')

In [18]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

#### changing datatype of array (from a array)

In [19]:
arr3 = arr2.astype('int')

In [20]:
arr3

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [21]:
arr4 = np.array(list2, dtype = 'bool')

In [22]:
arr4

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
list2

[[9, 0, 4, 6], [4, 6, 2, 1]]

In [24]:
arr5 = np.array([2, 5, 2.0, 'y'], dtype = 'object')

In [25]:
arr5

array([2, 5, 2.0, 'y'], dtype=object)

#### changing array to list

In [26]:
list3 = arr5.tolist()

In [27]:
list3

[2, 5, 2.0, 'y']

In [28]:
type(list3)

list

## 2.Array Dimentions

In [29]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

#### changing shape (row*col)

In [30]:
arr2.shape

(2, 4)

In [31]:
arr2.size

8

In [32]:
arr2.dtype

dtype('float64')

In [33]:
arr2.ndim

2

## 3.Reversing rows & Columns

In [34]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [35]:
arr2[::--1]

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [36]:
arr2[::-1]

array([[4., 6., 2., 1.],
       [9., 0., 4., 6.]])

In [37]:
arr2[::-1, ::-1]

array([[1., 2., 6., 4.],
       [6., 4., 0., 9.]])

## 4.Specific Element Extraction

In [38]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [39]:
arr2[0, :]

array([9., 0., 4., 6.])

In [40]:
arr2[:1, :]

array([[9., 0., 4., 6.]])

In [41]:
arr2[:2, :]

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [42]:
arr2[:-1, :]

array([[9., 0., 4., 6.]])

In [43]:
arr2[:, 3]

array([6., 1.])

In [44]:
arr2[:, 1]

array([0., 6.])

In [45]:
arr2[:, -1]

array([6., 1.])

In [46]:
arr2[:, 1:3]  #1,2

array([[0., 4.],
       [6., 2.]])

## 5. Basic Statistics

In [47]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [48]:
arr2.min()

0.0

In [49]:
arr2.max()

9.0

In [50]:
arr2.sum()

32.0

In [51]:
arr2.mean()

4.0

In [52]:
np.median(arr2)

4.0

In [54]:
np.average(arr2)

4.0

In [55]:
np.var(arr2)

7.75

## 6. Reshaping & flattering

In [56]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [57]:
arr2.shape

(2, 4)

In [58]:
arr2.reshape(4,2)

array([[9., 0.],
       [4., 6.],
       [4., 6.],
       [2., 1.]])

In [59]:
arr2.reshape(1,8)

array([[9., 0., 4., 6., 4., 6., 2., 1.]])

In [60]:
arr2.reshape(8,1)

array([[9.],
       [0.],
       [4.],
       [6.],
       [4.],
       [6.],
       [2.],
       [1.]])

In [61]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [64]:
f1 = arr2.flatten()

In [65]:
f1

array([9., 0., 4., 6., 4., 6., 2., 1.])

In [66]:
arr2.ndim

2

In [67]:
f1.ndim

1

## 7. Creating Random Arrays and Sequence

In [69]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
#np.arange(start,end,jump)

np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [72]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [73]:
#linspace(start, end, no. of elements) automatically calc the total jumps

np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [74]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#zeros(n,m) returns array of size n*m with all elements as 0

In [75]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [76]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## 8.Unique items and count

In [77]:
arr = [[1, 4 , 5, 2, 2 , 5],[4, 4 ,1, 7, 4, 5]]

In [78]:
arr

[[1, 4, 5, 2, 2, 5], [4, 4, 1, 7, 4, 5]]

In [79]:
u_val, count = np.unique(arr, return_counts = True)

In [80]:
u_val

array([1, 2, 4, 5, 7])

In [81]:
count

array([2, 2, 4, 3, 1], dtype=int64)